### ISSUE TITLE
zip a folder....zips the contents of folder?

### ISSUE THREAD

**Issue by vasilevich** [maugenst/zip-a-folder#25] opened 2021-04-20 06:02 UTC
your script makes no sense,
ZipAFolder, and zip goes inside the folder instead of zipping the folder,
usually zip archivers zip the insides of a folder only when the path has / at the end

for example
'build/' or 'build/*' should zip the contents only, making a zip containing the contents.
however
'build'
should make a zip with the folder 'build' similar to regular archivers.

**Comment by salmin89** [comment] 2023-08-17 17:29
The way this issue is written is rude and closing it makes sense. However I have a similar issue with this package, when it comes to working on my browser-extension.

Is there a way to request the feature to zip a folder?

**Comment by maugenst** [comment] 2023-08-17 19:49
Have you tried the new regex feature? This will probably solve the problem.

If not please explain in more detail what exactly the problem is.

**Comment by salmin89** [comment] 2023-08-18 13:33
```
const zip = require('zip-a-folder').zip;

class TestMe {

    static async main() {
        await zip('./entry', './dist/zip-a-folder.zip');
    }
}

TestMe.main();
```

In this picture I got two zips. One is from right clicking on the folder and selecting "Compress". The other one is from this line:
`await zip('./entry', './dist/zip-a-folder.zip');`


![image](https://github.com/maugenst/zip-a-folder/assets/10077295/cfa2676c-8a42-41ea-a5e7-8cd3eb76a51e)


I tried using archiver instead, and this code worked:

```
  // create dist based of this: https://github.com/archiverjs/node-archiver/issues/639
  archive.append(null, { name: 'dist/' });

  // append files from a sub-directory and naming it `new-subdir` within the archive
  archive.directory(`apps/${appName}/dist/`, 'dist/');
  ```
  
  Not sure how I can do this with the regex feature? mind sending me an example?

**Comment by maugenst** [comment] 2023-08-20 14:59
As I'm now away in holidays, I'll get back to you once I'm back.

**Comment by maugenst** [comment] 2023-09-18 14:04
With version 3.1.0 onwards there is the possibillity to specify a destination path (like archivejs is doing). You implicitly did this in your code, I added this to zip-a-folder as well to stay compatible. 
```js
import {zip} from 'zip-a-folder';

class TestMe {

    static async main() {
        // zip all json into an archive
        await zip('data/', '/path/to/archive.zip', {destPath: 'data/'});
    }
}

TestMe.main();
```

Feel free to reopen this issue if you encounter additional issues.

**Closed by maugenst** 2023-09-18 14:04 UTC
Labels: enhancement
